- name: install analytics
  block:

    - name: install analytics
      throttle: 1
      shell:
        cmd: /opt/apigee/apigee-setup/bin/setup.sh -p qs -f /tmp/apigee/config.conf
  when: 
    - inventory_hostname in groups.analytics
  tags:
    - install_all
    - analytics